name = "AutoHist"
uuid = "0bf0ee65-3559-4d1e-a282-1b0e88839781"
authors = ["Oskar HÃ¸gberg Simensen"]
version = "0.1.0-alpha"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
